language: cpp

os:
  - linux
  
compiler:
  - gcc 

script:     
  - qmake QMAKE_CXX=g++-4.8 QMAKE_C=gcc-4.8 PA193_test_parser_dash.pro
  - ./build_dir_tree.sh
  - make -j4
  - ./build/release/tests/tests
